executor: "cluster-generic"
cluster-generic-cancel-cmd: "scancel"
restart-times: "0"
jobscript: "slurm-jobscript.sh"
cluster-generic-submit-cmd: "slurm-submit.py"
cluster-generic-status-cmd: "slurm-status.py"
max-jobs-per-second: "10"
max-status-checks-per-second: "10"
local-cores: 1
latency-wait: "2"
use-conda: "False"
use-singularity: "False"
jobs: "384"
printshellcmds: "False"

default-resources:
  - runtime=7d
  - mem_mb=16384

# Example resource configuration
# default-resources:
#   - runtime=100
#   - mem_mb=6000
#   - disk_mb=1000000
# # set-threads: map rule names to threads
# set-threads:
#   - single_core_rule=1
#   - multi_core_rule=10
# # set-resources: map rule names to resources in general
# set-resources:
#   - high_memory_rule:mem_mb=12000
#   - long_running_rule:runtime=1200
